FROM golang:1.17-stretch AS builder
WORKDIR /dp-frontend-router
COPY . ./
RUN cd assets; go run github.com/jteeuwen/go-bindata/go-bindata -o redirects.go -pkg assets redirects/...
RUN go build -ldflags "-w -s -X 'main.BuildTime=$(date +%s)'" -tags 'debug' -o ./build .

FROM golang:1.17-stretch
WORKDIR /app
COPY --from=builder /dp-frontend-router/build .
EXPOSE 20000
ENTRYPOINT HUMAN_LOG=1 DEBUG=1 ./build 
