FROM node:14-buster As build
WORKDIR /app
COPY . /app
COPY package.json /app
RUN npm install && npm cache clean --force && npm run build

FROM node:14-alpine
COPY --from=build /app ./app/.
WORKDIR /app
CMD npm run dev
EXPOSE 9000