version: "3.3"
services:
  dp-search-reindex-api:
    build:
      context: ${ROOT_SEARCH_REINDEX_API:-../../../../dp-search-reindex-api}
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${ROOT_SEARCH_REINDEX_API:-../../../../dp-search-reindex-api}:/dp-search-reindex-api
    expose:
      - "25700"
    ports:
      - 25700:25700
    restart: unless-stopped
    environment:
      BIND_ADDR:          ":25700"
      ELASTIC_SEARCH_URL: ${ELASTIC_SEARCH_URL:-http://sitewideelasticsearch:9200}
      KAFKA_ADDR:         ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_VERSION:      ${KAFKA_VERSION:-3.1.0}
      SEARCH_API_URL: ${SEARCH_API_URL:-http://dp-search-api:23900}
      SERVICE_AUTH_TOKEN:                 $SERVICE_AUTH_TOKEN
      ZEBEDEE_URL:        ${ZEBEDEE_URL:-http://zebedee:8082}
      MONGODB_BIND_ADDR:           ${MONGODB_BIND_ADDR:-mongodb:27017}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:25700/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
